### ISSUE TITLE
Graphic interface

### ISSUE THREAD

**Issue by Aisyk** [RPCS3/rpcs3-binaries-linux#2] opened 2020-07-21 15:03 UTC
Hi !

I uses PopOS 20.04, and when i launch RPCS3, i have a buggy interface. Is there anything to do ?
![Capture d’écran du 2020-07-21 17-01-42](https://user-images.githubusercontent.com/5584650/88071371-05aba000-cb74-11ea-9f66-ad04ff4c552b.png)

**Comment by hcorion** [comment] 2020-11-22 22:52
Hey there, please close this issue.
Nobody checks this issue tracker, if you have any issues with RPCS3, please file them on the main issue tracker on https://github.com/RPCS3/rpcs3.

In regards to this issue, it's a duplicate of https://github.com/RPCS3/rpcs3/issues/8095 which has been fixed.

**Closed as completed** 2021-01-29 12:01 UTC
